# ~/.aerospace.toml
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
#                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
#                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
#                   sectionSign (ISO keyboards only, european keyboards only)
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut
# (like in i3)
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''

after-login-command = []
after-startup-command = []
start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = false

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 10
    inner.vertical = 10
    outer.left = 0
    outer.bottom = 0
    outer.top = 0
    outer.right = 0

[mode.main.binding]
    # Focus
    ctrl-h = 'focus left'
    ctrl-j = 'focus down'
    ctrl-k = 'focus up'
    ctrl-l = 'focus right'

    # Move
    ctrl-alt-h = 'move left'
    ctrl-alt-j = 'move down'
    ctrl-alt-k = 'move up'
    ctrl-alt-l = 'move right'

    # Resize
    ctrl-minus = 'resize smart -50'
    ctrl-equal = 'resize smart +50'

    # Workspace (nur Zahlen, keine Buchstaben, um Konflikte zu vermeiden)
    ctrl-1 = 'workspace Desktop'
    ctrl-2 = 'workspace Work'
    ctrl-3 = 'workspace Music'
    ctrl-4 = 'workspace 4'
    ctrl-5 = 'workspace 5'
    ctrl-6 = 'workspace 6'
    ctrl-7 = 'workspace 7'
    ctrl-8 = 'workspace 8'
    ctrl-9 = 'workspace 9'
    ctrl-s = 'workspace Messages'
    ctrl-b = 'workspace Browser'
    ctrl-v = 'workspace VSCode'
    ctrl-f = 'workspace Finder'
    ctrl-m = 'workspace Mail'

    ctrl-alt-1 = 'move-node-to-workspace Desktop'
    ctrl-alt-2 = 'move-node-to-workspace Work'
    ctrl-alt-3 = 'move-node-to-workspace Music'
    ctrl-alt-4 = 'move-node-to-workspace 4'
    ctrl-alt-5 = 'move-node-to-workspace 5'
    ctrl-alt-6 = 'move-node-to-workspace 6'
    ctrl-alt-7 = 'move-node-to-workspace 7'
    ctrl-alt-8 = 'move-node-to-workspace 8'
    ctrl-alt-9 = 'move-node-to-workspace 9'
    ctrl-alt-s = 'move-node-to-workspace Messages'
    ctrl-alt-b = 'move-node-to-workspace Browser'
    ctrl-alt-v = 'move-node-to-workspace VSCode'
    ctrl-alt-f = 'move-node-to-workspace Finder'
    ctrl-alt-m = 'move-node-to-workspace Mail'

    # Layout
    ctrl-slash = 'layout tiles horizontal vertical'
    ctrl-comma = 'layout accordion horizontal vertical'

    # Workspace back and forth
    ctrl-tab = 'workspace-back-and-forth'
    ctrl-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # Mode
    ctrl-shift-semicolon = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main']
    f = ['layout floating tiling', 'mode main']
    backspace = ['close-all-windows-but-current', 'mode main']
    ctrl-alt-h = ['join-with left', 'mode main']
    ctrl-alt-j = ['join-with down', 'mode main']
    ctrl-alt-k = ['join-with up', 'mode main']
    ctrl-alt-l = ['join-with right', 'mode main']
    down = 'volume down'
    up = 'volume up'
    shift-down = ['volume set 0', 'mode main']